language: rust
rust:
- stable
before_script:
- rustup component add clippy
script:
- cargo build --verbose --all
- cargo clippy --all-targets --all-features -- -D warnings
- cargo test --verbose --all