[package]
name = "csp_generator"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[lib]
bench = false
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"