name: Build and Test Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup component add clippy
      - run: rustup component add rustfmt
      - run: cargo build
      - run: cargo test
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings